jobs:
  TestCluster:
    docker: 
      - image: aws-eks/python3
    steps:
      - add_ssh_keys:
         fingerprints:
           - "82:d3:09:f6:29:a4:39:91:c8:61:4b:17:fa:f8:e9:02"
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: Cluster_Desarrollo
      - run:
          command: |
            kubectl get services
  ProductionEnvironment:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
         fingerprints:
           - "82:d3:09:f6:29:a4:39:91:c8:61:4b:17:fa:f8:e9:02"
      - checkout
      - run:
         name: "Ejecucion" 
         command: |           
           scp -o StrictHostKeyChecking=no .circleci/index.html ubuntu@3.87.1.16:/var/www/html/index.html
  DevelopmentEnvironment:
    docker:
      - image: circleci/openjdk
    steps:
      - add_ssh_keys:
         fingerprints:
           - "82:d3:09:f6:29:a4:39:91:c8:61:4b:17:fa:f8:e9:02"
      - checkout
      - run:
         name: "Ejecucion" 
         command: |          
           scp -o StrictHostKeyChecking=no .circleci/index.html ubuntu@52.87.244.81:/var/www/html/index.html
workflows:
  version: 2
  build: 
    jobs:
      - DevelopmentEnvironment
      - request-testing:
          type: approval
          requires:
            - DevelopmentEnvironment
      - ProductionEnvironment:
          requires:
            - request-testing
