apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: deploymentuno
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: front-end
          image: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-front-end
              mountPath: /etc/nginx/conf.d
        - name: app1
          image: httpd:2.4
          ports:
            - containerPort: 3000
      volume:
        - name: nginx-front-end
          configMap:
            name: nginx-configuration
            items:
              - key: nginx-default.conf
                path: default.conf
